// Generated by refresh-supplier.js on 2026-09-17T04:04:02.066Z
window.SUPPLIER_SNAPSHOT = {
  "fetchedAt": "2026-09-17T04:04:02.066Z",
  "site": "https://superspeciosa.com",
  "freeShipping": "",
  "promos": [
    {
      "title": "20% OFF KAVA GUMMIES",
      "percent": 20,
      "discountType": "PERCENTAGE",
      "startsAt": "2026-09-16T04:00:00Z",
      "endsAt": "2026-09-17T04:00:00Z",
      "status": null,
      "products": [
        {
          "handle": "lemon-lime-kava-gummies",
          "title": "Lemon Lime Kava Gummies"
        }
      ]
    },
    {
      "title": "20% Off Enhanced Capsules + 30-count gummies",
      "percent": 20,
      "discountType": "PERCENTAGE",
      "startsAt": "2026-09-18T04:00:00Z",
      "endsAt": "2026-09-19T04:00:00Z",
      "status": null,
      "products": [
        {
          "handle": "bold-blueberry-kratom-gummies",
          "title": "Blueberry Extra Strength Kratom Gummies"
        },
        {
          "handle": "emerald-select-enhanced-kratom-capsules",
          "title": "Emerald Select Enhanced Kratom Capsules"
        },
        {
          "handle": "lemon-lime-kava-gummies",
          "title": "Lemon Lime Kava Gummies"
        },
        {
          "handle": "mango-extra-strength-kratom-gummies",
          "title": "Mango Extra Strength Kratom Gummies"
        },
        {
          "handle": "red-gem-enhanced-kratom-capsules",
          "title": "Red Gem Enhanced Kratom Capsules"
        },
        {
          "handle": "strawberry-extra-strength-kratom-gummies",
          "title": "Strawberry Extra Strength Kratom Gummies"
        }
      ]
    },
    {
      "title": "40% OFF WHITE THAI",
      "percent": 40,
      "discountType": "PERCENTAGE",
      "startsAt": "2026-09-23T04:00:00Z",
      "endsAt": "2026-09-24T04:00:00Z",
      "status": null,
      "products": [
        {
          "handle": "white-thai-kratom-capsules",
          "title": "White Thai Kratom Capsules"
        },
        {
          "handle": "white-thai-kratom-powder",
          "title": "White Thai Kratom Powder"
        },
        {
          "handle": "white-thai-kratom-tablets",
          "title": "White Thai Kratom Tablets"
        }
      ]
    },
    {
      "title": "25% OFF SIGNATURE RESERVE",
      "percent": 25,
      "discountType": "PERCENTAGE",
      "startsAt": "2026-09-25T04:00:00Z",
      "endsAt": "2026-09-26T04:00:00Z",
      "status": "SCHEDULED",
      "products": [
        {
          "handle": "super-speciosa-kratom-capsules",
          "title": "Signature Reserve Kratom Capsules"
        },
        {
          "handle": "super-speciosa-kratom-powder",
          "title": "Signature Reserve Kratom Powder"
        }
      ]
    }
  ],
  "products": {
    "lemon-lime-kava-gummies": {
      "title": "Lemon Lime Kava Gummies",
      "variants": [
        {
          "id": 48362781016285,
          "title": "30 count",
          "form": "caps",
          "count": 30,
          "grams": null,
          "label": "30ct",
          "price": 39.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 48362781049053,
          "title": "60 count",
          "form": "caps",
          "count": 60,
          "grams": null,
          "label": "60ct",
          "price": 67.98,
          "compareAt": null,
          "available": true
        },
        {
          "id": 48362781081821,
          "title": "90 count",
          "form": "caps",
          "count": 90,
          "grams": null,
          "label": "90ct",
          "price": 95.97,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "super-speciosa-kratom-powder": {
      "title": "Signature Reserve Kratom Powder",
      "variants": [
        {
          "id": 46868026360029,
          "title": "100g (3.5oz)",
          "form": "powder",
          "count": 200,
          "grams": 100,
          "label": "100g powder",
          "price": 24.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454103773,
          "title": "250g (8.8 oz)",
          "form": "powder",
          "count": 500,
          "grams": 250,
          "label": "250g powder",
          "price": 49.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454136541,
          "title": "500g (1.1 lbs)",
          "form": "powder",
          "count": 1000,
          "grams": 500,
          "label": "500g powder",
          "price": 79.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454169309,
          "title": "1 kilogram (2.2 lbs)",
          "form": "powder",
          "count": 2000,
          "grams": 1000,
          "label": "1000g powder",
          "price": 154.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "super-red-kratom-powder": {
      "title": "Super Red Kratom Powder",
      "variants": [
        {
          "id": 45355460624605,
          "title": "100g (3.5 oz)",
          "form": "powder",
          "count": 200,
          "grams": 100,
          "label": "100g powder",
          "price": 24.99,
          "compareAt": null,
          "available": false
        },
        {
          "id": 45355460657373,
          "title": "250g (8.8 oz)",
          "form": "powder",
          "count": 500,
          "grams": 250,
          "label": "250g powder",
          "price": 49.99,
          "compareAt": null,
          "available": false
        },
        {
          "id": 45355460690141,
          "title": "1 kilogram (2.2 lbs)",
          "form": "powder",
          "count": 2000,
          "grams": 1000,
          "label": "1000g powder",
          "price": 154.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "super-red-kratom-capsules": {
      "title": "Super Red Kratom Capsules",
      "variants": [
        {
          "id": 45636589486301,
          "title": "60 count (30g)",
          "form": "caps",
          "count": 60,
          "grams": null,
          "label": "60ct",
          "price": 24.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45636589519069,
          "title": "320 count (160g)",
          "form": "caps",
          "count": 320,
          "grams": null,
          "label": "320ct",
          "price": 89.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45636589551837,
          "title": "1000 count (500g)",
          "form": "caps",
          "count": 1000,
          "grams": null,
          "label": "1000ct",
          "price": 189.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "white-thai-kratom-capsules": {
      "title": "White Thai Kratom Capsules",
      "variants": [
        {
          "id": 45355457183965,
          "title": "60 count (30g)",
          "form": "caps",
          "count": 60,
          "grams": null,
          "label": "60ct",
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355457249501,
          "title": "320 count (160g)",
          "form": "caps",
          "count": 320,
          "grams": null,
          "label": "320ct",
          "price": 58.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355457282269,
          "title": "1000 count (500g)",
          "form": "caps",
          "count": 1000,
          "grams": null,
          "label": "1000ct",
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "white-maeng-da-kratom-capsules": {
      "title": "White Maeng Da Kratom Capsules",
      "variants": [
        {
          "id": 45355457315037,
          "title": "60 count (30g)",
          "form": "caps",
          "count": 60,
          "grams": null,
          "label": "60ct",
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355457380573,
          "title": "320 count (160g)",
          "form": "caps",
          "count": 320,
          "grams": null,
          "label": "320ct",
          "price": 58.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355457413341,
          "title": "1000 count (500g)",
          "form": "caps",
          "count": 1000,
          "grams": null,
          "label": "1000ct",
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "red-bali-kratom-capsules": {
      "title": "Red Bali Kratom Capsules",
      "variants": [
        {
          "id": 45355456823517,
          "title": "60 count (30g)",
          "form": "caps",
          "count": 60,
          "grams": null,
          "label": "60ct",
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456889053,
          "title": "320 count (160g)",
          "form": "caps",
          "count": 320,
          "grams": null,
          "label": "320ct",
          "price": 58.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456954589,
          "title": "1000 count (500g)",
          "form": "caps",
          "count": 1000,
          "grams": null,
          "label": "1000ct",
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "red-borneo-kratom-capsules": {
      "title": "Red Borneo Kratom Capsules",
      "variants": [
        {
          "id": 45355456921821,
          "title": "60 count (30g)",
          "form": "caps",
          "count": 60,
          "grams": null,
          "label": "60ct",
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355457020125,
          "title": "320 count (160g)",
          "form": "caps",
          "count": 320,
          "grams": null,
          "label": "320ct",
          "price": 59,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355457052893,
          "title": "1000 count (500g)",
          "form": "caps",
          "count": 1000,
          "grams": null,
          "label": "1000ct",
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "red-maeng-da-kratom-capsules": {
      "title": "Buy Red Maeng Da Kratom Capsules",
      "variants": [
        {
          "id": 45355456659677,
          "title": "60 count (30g)",
          "form": "caps",
          "count": 60,
          "grams": null,
          "label": "60ct",
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456725213,
          "title": "320 count (160g)",
          "form": "caps",
          "count": 320,
          "grams": null,
          "label": "320ct",
          "price": 58.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456757981,
          "title": "1000 count (500g)",
          "form": "caps",
          "count": 1000,
          "grams": null,
          "label": "1000ct",
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "super-speciosa-kratom-capsules": {
      "title": "Signature Reserve Kratom Capsules",
      "variants": [
        {
          "id": 45355456561373,
          "title": "60 count (30g)",
          "form": "caps",
          "count": 60,
          "grams": null,
          "label": "60ct",
          "price": 24.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456594141,
          "title": "320 count (160g)",
          "form": "caps",
          "count": 320,
          "grams": null,
          "label": "320ct",
          "price": 89.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456626909,
          "title": "1000 count (500g)",
          "form": "caps",
          "count": 1000,
          "grams": null,
          "label": "1000ct",
          "price": 189.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "premium-bali-kratom-capsules": {
      "title": "Green Bali Kratom Capsules",
      "variants": [
        {
          "id": 45355456364765,
          "title": "60 count (30g)",
          "form": "caps",
          "count": 60,
          "grams": null,
          "label": "60ct",
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456463069,
          "title": "320 count (160g)",
          "form": "caps",
          "count": 320,
          "grams": null,
          "label": "320ct",
          "price": 58.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456495837,
          "title": "1000 count (500g)",
          "form": "caps",
          "count": 1000,
          "grams": null,
          "label": "1000ct",
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "green-malay-kratom-capsules": {
      "title": "Green Malay Kratom Capsules",
      "variants": [
        {
          "id": 45355456233693,
          "title": "60 count (30g)",
          "form": "caps",
          "count": 60,
          "grams": null,
          "label": "60ct",
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456299229,
          "title": "320 count (160g)",
          "form": "caps",
          "count": 320,
          "grams": null,
          "label": "320ct",
          "price": 59,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456331997,
          "title": "1000 count (500g)",
          "form": "caps",
          "count": 1000,
          "grams": null,
          "label": "1000ct",
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "green-maeng-da-kratom-capsules": {
      "title": "Green Maeng Da Kratom Capsules",
      "variants": [
        {
          "id": 45355456037085,
          "title": "60 count (30g)",
          "form": "caps",
          "count": 60,
          "grams": null,
          "label": "60ct",
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456102621,
          "title": "320 count (160g)",
          "form": "caps",
          "count": 320,
          "grams": null,
          "label": "320ct",
          "price": 58.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456135389,
          "title": "1000 count (500g)",
          "form": "caps",
          "count": 1000,
          "grams": null,
          "label": "1000ct",
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "red-bali-kratom-powder": {
      "title": "Red Bali Kratom Powder",
      "variants": [
        {
          "id": 45355455676637,
          "title": "100g (3.5 oz)",
          "form": "powder",
          "count": 200,
          "grams": 100,
          "label": "100g powder",
          "price": 19.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355455709405,
          "title": "250g (8.8 oz)",
          "form": "powder",
          "count": 500,
          "grams": 250,
          "label": "250g powder",
          "price": 39.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355455742173,
          "title": "1 kilogram (2.2 lbs)",
          "form": "powder",
          "count": 2000,
          "grams": 1000,
          "label": "1000g powder",
          "price": 139.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355455774941,
          "title": "5 kilograms (11 lbs)",
          "form": "powder",
          "count": 10000,
          "grams": 5000,
          "label": "5000g powder",
          "price": 499,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "red-borneo-kratom-powder": {
      "title": "Red Borneo Kratom Powder",
      "variants": [
        {
          "id": 45355455152349,
          "title": "100g (3.5 oz)",
          "form": "powder",
          "count": 200,
          "grams": 100,
          "label": "100g powder",
          "price": 19.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355455185117,
          "title": "250g (8.8 oz)",
          "form": "powder",
          "count": 500,
          "grams": 250,
          "label": "250g powder",
          "price": 39.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355455217885,
          "title": "1 kilogram (2.2 lbs)",
          "form": "powder",
          "count": 2000,
          "grams": 1000,
          "label": "1000g powder",
          "price": 139.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355455250653,
          "title": "5 kilograms (11 lbs)",
          "form": "powder",
          "count": 10000,
          "grams": 5000,
          "label": "5000g powder",
          "price": 499,
          "compareAt": null,
          "available": false
        }
      ]
    },
    "green-malay-kratom-powder": {
      "title": "Green Malay Kratom Powder",
      "variants": [
        {
          "id": 45355454791901,
          "title": "100g (3.5 oz)",
          "form": "powder",
          "count": 200,
          "grams": 100,
          "label": "100g powder",
          "price": 19.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454824669,
          "title": "250g (8.8 oz)",
          "form": "powder",
          "count": 500,
          "grams": 250,
          "label": "250g powder",
          "price": 39.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454857437,
          "title": "1 kilogram (2.2 lbs)",
          "form": "powder",
          "count": 2000,
          "grams": 1000,
          "label": "1000g powder",
          "price": 139.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454890205,
          "title": "5 kilograms (11 lbs)",
          "form": "powder",
          "count": 10000,
          "grams": 5000,
          "label": "5000g powder",
          "price": 499,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "white-thai-kratom-powder": {
      "title": "White Thai Kratom Powder",
      "variants": [
        {
          "id": 45355454628061,
          "title": "100g (3.5 oz)",
          "form": "powder",
          "count": 200,
          "grams": 100,
          "label": "100g powder",
          "price": 19.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454660829,
          "title": "250g (8.8 oz)",
          "form": "powder",
          "count": 500,
          "grams": 250,
          "label": "250g powder",
          "price": 39.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454693597,
          "title": "1 kilogram (2.2 lbs)",
          "form": "powder",
          "count": 2000,
          "grams": 1000,
          "label": "1000g powder",
          "price": 139.99,
          "compareAt": null,
          "available": false
        },
        {
          "id": 45355454726365,
          "title": "5 kilograms (11 lbs)",
          "form": "powder",
          "count": 10000,
          "grams": 5000,
          "label": "5000g powder",
          "price": 499,
          "compareAt": null,
          "available": false
        }
      ]
    },
    "premium-bali-kratom-powder": {
      "title": "Green Bali Kratom Powder",
      "variants": [
        {
          "id": 45355454464221,
          "title": "100g (3.5 oz)",
          "form": "powder",
          "count": 200,
          "grams": 100,
          "label": "100g powder",
          "price": 19.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454496989,
          "title": "250g (8.8 oz)",
          "form": "powder",
          "count": 500,
          "grams": 250,
          "label": "250g powder",
          "price": 39.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454529757,
          "title": "1 kilogram (2.2 lbs)",
          "form": "powder",
          "count": 2000,
          "grams": 1000,
          "label": "1000g powder",
          "price": 139.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454562525,
          "title": "5 kilograms (11 lbs)",
          "form": "powder",
          "count": 10000,
          "grams": 5000,
          "label": "5000g powder",
          "price": 499,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "white-maeng-da-kratom-powder": {
      "title": "White Maeng Da Kratom Powder",
      "variants": [
        {
          "id": 45355454267613,
          "title": "100g (3.5 oz)",
          "form": "powder",
          "count": 200,
          "grams": 100,
          "label": "100g powder",
          "price": 19.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454300381,
          "title": "250g (8.8 oz)",
          "form": "powder",
          "count": 500,
          "grams": 250,
          "label": "250g powder",
          "price": 39.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454333149,
          "title": "1 kilogram (2.2 lbs)",
          "form": "powder",
          "count": 2000,
          "grams": 1000,
          "label": "1000g powder",
          "price": 139.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355454365917,
          "title": "5 kilograms (11 lbs)",
          "form": "powder",
          "count": 10000,
          "grams": 5000,
          "label": "5000g powder",
          "price": 499,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "red-maeng-da-kratom-powder": {
      "title": "Red Maeng Da Kratom Powder",
      "variants": [
        {
          "id": 45355453874397,
          "title": "100g (3.5 oz)",
          "form": "powder",
          "count": 200,
          "grams": 100,
          "label": "100g powder",
          "price": 19.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355453907165,
          "title": "250g (8.8 oz)",
          "form": "powder",
          "count": 500,
          "grams": 250,
          "label": "250g powder",
          "price": 39.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355453939933,
          "title": "1 kilogram (2.2 lbs)",
          "form": "powder",
          "count": 2000,
          "grams": 1000,
          "label": "1000g powder",
          "price": 139.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355453972701,
          "title": "5 kilograms (11 lbs)",
          "form": "powder",
          "count": 10000,
          "grams": 5000,
          "label": "5000g powder",
          "price": 499,
          "compareAt": null,
          "available": false
        }
      ]
    },
    "green-maeng-da-kratom-powder": {
      "title": "Green Maeng Da Kratom Powder",
      "variants": [
        {
          "id": 45355453710557,
          "title": "100g (3.5 oz)",
          "form": "powder",
          "count": 200,
          "grams": 100,
          "label": "100g powder",
          "price": 19.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355453743325,
          "title": "250g (8.8 oz)",
          "form": "powder",
          "count": 500,
          "grams": 250,
          "label": "250g powder",
          "price": 39.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355453776093,
          "title": "1 kilogram (2.2 lbs)",
          "form": "powder",
          "count": 2000,
          "grams": 1000,
          "label": "1000g powder",
          "price": 139.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355453808861,
          "title": "5 kilograms (11 lbs)",
          "form": "powder",
          "count": 10000,
          "grams": 5000,
          "label": "5000g powder",
          "price": 499,
          "compareAt": null,
          "available": true
        }
      ]
    }
  }
};
