// Generated by refresh-supplier.js on 2026-09-17T03:28:43.872Z
window.SUPPLIER_SNAPSHOT = {
  "fetchedAt": "2026-09-17T03:28:43.872Z",
  "site": "https://superspeciosa.com",
  "freeShipping": "",
  "promos": [
    {
      "title": "20% OFF KAVA GUMMIES",
      "percent": 20,
      "discountType": "PERCENTAGE",
      "startsAt": "2026-09-16T04:00:00Z",
      "endsAt": "2026-09-17T04:00:00Z",
      "status": null,
      "products": [
        {
          "handle": "lemon-lime-kava-gummies",
          "title": "Lemon Lime Kava Gummies"
        }
      ]
    },
    {
      "title": "20% Off Enhanced Capsules + 30-count gummies",
      "percent": 20,
      "discountType": "PERCENTAGE",
      "startsAt": "2026-09-18T04:00:00Z",
      "endsAt": "2026-09-19T04:00:00Z",
      "status": null,
      "products": [
        {
          "handle": "bold-blueberry-kratom-gummies",
          "title": "Blueberry Extra Strength Kratom Gummies"
        },
        {
          "handle": "emerald-select-enhanced-kratom-capsules",
          "title": "Emerald Select Enhanced Kratom Capsules"
        },
        {
          "handle": "lemon-lime-kava-gummies",
          "title": "Lemon Lime Kava Gummies"
        },
        {
          "handle": "mango-extra-strength-kratom-gummies",
          "title": "Mango Extra Strength Kratom Gummies"
        },
        {
          "handle": "red-gem-enhanced-kratom-capsules",
          "title": "Red Gem Enhanced Kratom Capsules"
        },
        {
          "handle": "strawberry-extra-strength-kratom-gummies",
          "title": "Strawberry Extra Strength Kratom Gummies"
        }
      ]
    },
    {
      "title": "40% OFF WHITE THAI",
      "percent": 40,
      "discountType": "PERCENTAGE",
      "startsAt": "2026-09-23T04:00:00Z",
      "endsAt": "2026-09-24T04:00:00Z",
      "status": null,
      "products": [
        {
          "handle": "white-thai-kratom-capsules",
          "title": "White Thai Kratom Capsules"
        },
        {
          "handle": "white-thai-kratom-powder",
          "title": "White Thai Kratom Powder"
        },
        {
          "handle": "white-thai-kratom-tablets",
          "title": "White Thai Kratom Tablets"
        }
      ]
    },
    {
      "title": "25% OFF SIGNATURE RESERVE",
      "percent": 25,
      "discountType": "PERCENTAGE",
      "startsAt": "2026-09-25T04:00:00Z",
      "endsAt": "2026-09-26T04:00:00Z",
      "status": "SCHEDULED",
      "products": [
        {
          "handle": "super-speciosa-kratom-capsules",
          "title": "Signature Reserve Kratom Capsules"
        },
        {
          "handle": "super-speciosa-kratom-powder",
          "title": "Signature Reserve Kratom Powder"
        }
      ]
    }
  ],
  "products": {
    "lemon-lime-kava-gummies": {
      "title": "Lemon Lime Kava Gummies",
      "variants": [
        {
          "id": 48362781016285,
          "title": "30 count",
          "count": 30,
          "price": 39.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 48362781049053,
          "title": "60 count",
          "count": 60,
          "price": 67.98,
          "compareAt": null,
          "available": true
        },
        {
          "id": 48362781081821,
          "title": "90 count",
          "count": 90,
          "price": 95.97,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "super-red-kratom-capsules": {
      "title": "Super Red Kratom Capsules",
      "variants": [
        {
          "id": 45636589486301,
          "title": "60 count (30g)",
          "count": 60,
          "price": 24.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45636589519069,
          "title": "320 count (160g)",
          "count": 320,
          "price": 89.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45636589551837,
          "title": "1000 count (500g)",
          "count": 1000,
          "price": 189.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "white-thai-kratom-capsules": {
      "title": "White Thai Kratom Capsules",
      "variants": [
        {
          "id": 45355457183965,
          "title": "60 count (30g)",
          "count": 60,
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355457249501,
          "title": "320 count (160g)",
          "count": 320,
          "price": 58.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355457282269,
          "title": "1000 count (500g)",
          "count": 1000,
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "white-maeng-da-kratom-capsules": {
      "title": "White Maeng Da Kratom Capsules",
      "variants": [
        {
          "id": 45355457315037,
          "title": "60 count (30g)",
          "count": 60,
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355457380573,
          "title": "320 count (160g)",
          "count": 320,
          "price": 58.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355457413341,
          "title": "1000 count (500g)",
          "count": 1000,
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "red-bali-kratom-capsules": {
      "title": "Red Bali Kratom Capsules",
      "variants": [
        {
          "id": 45355456823517,
          "title": "60 count (30g)",
          "count": 60,
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456889053,
          "title": "320 count (160g)",
          "count": 320,
          "price": 58.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456954589,
          "title": "1000 count (500g)",
          "count": 1000,
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "red-borneo-kratom-capsules": {
      "title": "Red Borneo Kratom Capsules",
      "variants": [
        {
          "id": 45355456921821,
          "title": "60 count (30g)",
          "count": 60,
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355457020125,
          "title": "320 count (160g)",
          "count": 320,
          "price": 59,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355457052893,
          "title": "1000 count (500g)",
          "count": 1000,
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "red-maeng-da-kratom-capsules": {
      "title": "Buy Red Maeng Da Kratom Capsules",
      "variants": [
        {
          "id": 45355456659677,
          "title": "60 count (30g)",
          "count": 60,
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456725213,
          "title": "320 count (160g)",
          "count": 320,
          "price": 58.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456757981,
          "title": "1000 count (500g)",
          "count": 1000,
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "super-speciosa-kratom-capsules": {
      "title": "Signature Reserve Kratom Capsules",
      "variants": [
        {
          "id": 45355456561373,
          "title": "60 count (30g)",
          "count": 60,
          "price": 24.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456594141,
          "title": "320 count (160g)",
          "count": 320,
          "price": 89.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456626909,
          "title": "1000 count (500g)",
          "count": 1000,
          "price": 189.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "premium-bali-kratom-capsules": {
      "title": "Green Bali Kratom Capsules",
      "variants": [
        {
          "id": 45355456364765,
          "title": "60 count (30g)",
          "count": 60,
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456463069,
          "title": "320 count (160g)",
          "count": 320,
          "price": 58.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456495837,
          "title": "1000 count (500g)",
          "count": 1000,
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "green-malay-kratom-capsules": {
      "title": "Green Malay Kratom Capsules",
      "variants": [
        {
          "id": 45355456233693,
          "title": "60 count (30g)",
          "count": 60,
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456299229,
          "title": "320 count (160g)",
          "count": 320,
          "price": 59,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456331997,
          "title": "1000 count (500g)",
          "count": 1000,
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    },
    "green-maeng-da-kratom-capsules": {
      "title": "Green Maeng Da Kratom Capsules",
      "variants": [
        {
          "id": 45355456037085,
          "title": "60 count (30g)",
          "count": 60,
          "price": 16,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456102621,
          "title": "320 count (160g)",
          "count": 320,
          "price": 58.99,
          "compareAt": null,
          "available": true
        },
        {
          "id": 45355456135389,
          "title": "1000 count (500g)",
          "count": 1000,
          "price": 119.99,
          "compareAt": null,
          "available": true
        }
      ]
    }
  }
};
